package com.yang.mapper;

import com.yang.pojo.Activity;
import com.yang.pojo.ActivityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    Activity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Jun 23 17:11:36 CST 2022
     */
    int updateByPrimaryKey(Activity record);

    /**
     * 保存创建的市场活动
     */
    int insertActivity(Activity activity);

    /**
     * 查询分页
     */
    List<Activity> selectActivityByConditionForPage(Map<String,Object> map);

    /**
     * 查询总条数
     */
    int selectAllCounts(Map<String,Object> map);

    /**
     * 删除
     */
    int deleteById(String[] ids);

    /**
     * 根据ID查询市场活动信息
     */
    Activity selectActivityById(String id);


    /**
     * 更新
     */
    int updateById(Activity activity);

    /**
     * 查询所有activity(导出）
     */
    List<Activity> selectAllActivity();

    /**
     * 导入市场活动
     */
    int insertActivityByList(List<Activity> activityList);

    /**
     * detail
     */
    Activity selectActivityByIdForDetail(String id);

    /**
     * 根据clueId查询该线索相关联的市场活动的明细信息
     */
    List<Activity> selectActivityForDetailByClueId(String clueId);

    /**
     * 模糊查询关联市场活动
     */
    List<Activity> selectActivityForConvertByNameClueId(Map<String,Object> map) ;

    /**
     *根据ids查询市场活动的明细信息
     */
    List<Activity> selectActivityForDetailByIds(String[] ids);

    /**
     * 模糊查询2
     */
    List<Activity> selectActivityForDetailByNameClueId(Map<String,Object> map);

}