package com.yang.mapper;

import com.yang.pojo.ActivityRemark;
import com.yang.pojo.ActivityRemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int countByExample(ActivityRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int deleteByExample(ActivityRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int insert(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int insertSelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    List<ActivityRemark> selectByExample(ActivityRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int updateByExampleSelective(@Param("record") ActivityRemark record, @Param("example") ActivityRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int updateByExample(@Param("record") ActivityRemark record, @Param("example") ActivityRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int updateByPrimaryKeySelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Jun 28 09:10:57 CST 2022
     */
    int updateByPrimaryKey(ActivityRemark record);

    /**
     * 查询市场活动备注
     */
    List<ActivityRemark> selectActivityRemarkForDetailByActivityId(String activityId);

    /**
     * 保存创建的市场活动备注
     */
    int insertActivityRemark(ActivityRemark activityRemark);

    /**
     * 删除备注
     */
    int deleteActivityRemarkById(String id);

    /**
     * 更新备注
     */
    int updateActivityRemark(ActivityRemark activityRemark);
}